apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metabase
  template:
    metadata:
      labels:
        name: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
          - port: 80
            targetPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 120
          timeoutSeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
  name: metabase
spec:
  selector:
    name: metabase
  ports:
  - port: 80
    targetPort: 3000

